# Generated by Django 4.2.1 on 2023-09-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('Desc', models.CharField(max_length=500, null=True)),
                ('img', models.CharField(max_length=500, null=True)),
                ('red', models.CharField(default='default', max_length=100)),
                ('blocked', models.CharField(default='A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14,A15,A16,A17,B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B14,B15,B16,B17,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,', max_length=10000, null=True)),
                ('entered', models.BigIntegerField(default=0)),
                ('scanned', models.BigIntegerField(default=0)),
                ('cancels', models.BigIntegerField(default=0)),
                ('updatedon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('event',)},
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent1', models.CharField(max_length=200)),
                ('Parent2', models.CharField(blank=True, max_length=200)),
                ('Guardians', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.events')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('event', 'group')},
            },
        ),
        migrations.CreateModel(
            name='linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.CharField(blank=True, max_length=10, null=True)),
                ('whenbooked', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('emailsent', models.DateTimeField(blank=True, null=True)),
                ('scanned', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.events')),
                ('fami', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.family')),
                ('grp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.groupeventlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
