# Generated by Django 4.2.1 on 2023-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='QRscanned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='SeatsBooked',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='Seatscancelled',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='emailsent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='logins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='logouts',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='general',
            name='whenupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
