# Generated by Django 4.2.1 on 2023-11-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_general_qrscanned_general_seatsbooked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkage',
            name='maxseats',
            field=models.IntegerField(default=0),
        ),
    ]
