# Generated by Django 4.2.1 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_linkage_maxseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkage',
            name='maxseats',
            field=models.IntegerField(default=2),
        ),
    ]
