# Generated by Django 4.2.1 on 2023-11-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_linkage_maxseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='notifymail',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
