# Generated by Django 4.2.1 on 2023-11-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_events_notifymail'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='siblingsbooked',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='events',
            name='notifymail',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
