# Generated by Django 4.2.2 on 2023-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_events_siblingsbooked_alter_events_notifymail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='notifymail',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='siblingsbooked',
            field=models.CharField(blank=True, default='', max_length=1000000, null=True),
        ),
    ]
