# Generated by Django 4.2.1 on 2024-03-14 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('homepage', '0008_alter_events_notifymail_alter_events_siblingsbooked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeventlink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
