# Generated by Django 4.2.1 on 2024-03-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_groupeventlink_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkage',
            name='grp',
        ),
    ]
