# Generated by Django 4.2.1 on 2024-03-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0010_remove_linkage_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.events'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.events'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
