# Generated by Django 4.2.1 on 2024-03-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('homepage', '0011_alter_groupeventlink_event_alter_linkage_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeventlink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
