# Generated by Django 4.2.1 on 2024-03-18 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_alter_groupeventlink_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.events'),
        ),
    ]
