# Generated by Django 5.1 on 2024-10-30 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_alter_linkage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkage',
            name='grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.groupeventlink'),
        ),
    ]
