# Generated by Django 5.1 on 2024-10-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_linkage_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkage',
            name='grp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.groupeventlink'),
        ),
    ]
