# Generated by Django 5.1 on 2024-12-03 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_linkage_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkage',
            name='grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.groupeventlink'),
        ),
    ]
